# Dockerfile.dev
FROM node:18

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier tout le code source
COPY . .

# Exposer le port pour Vite
EXPOSE 3000

# Commande pour lancer Vite en mode développement
CMD ["npm", "run", "dev"]
