services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:80" # Accès au frontend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3002:3000" # Accès au backend
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
